### PR TITLE
Fix to allow assigning dicts to namelist groups

### PR DESCRIPTION
**Pull request by jamesp**
In version 0.19 it was possible to assign a dict to a namelist group and
write it out.  This fix allows the same behaviour in 0.21.

An example:

```python
import f90nml

namelist = f90nml.Namelist()

namelist['main_nml'] = {
     'days'   : 30,
     'hours'  : 0,
     'minutes': 0,
     'seconds': 0,
     'dt':720,
}

namelist.write('base.nml')
```

This used to work in version 0.19, now doesn't in version 0.21 (error message below).  PR fixes this by casting `dict` to `Namelist` when assigned to a key in the namelist.

```
$ python nml_test.py
Traceback (most recent call last):
  File "nml_test.py", line 15, in <module>
    namelist.write('base.nml')
  File "/f90nml/f90nml/namelist.py", line 232, in write
    self.write_nmlgrp(grp_name, grp_vars, nml_file)
  File "/f90nml/f90nml/namelist.py", line 251, in write_nmlgrp
    v_start = grp_vars.start_index.get(v_name, None)
AttributeError: 'dict' object has no attribute 'start_index'
```

### CODE REVIEW

**Comment by marshallward** [comment]
Great, thanks very much for this (especially for adding the test case!).

**Comment by jamesp** [comment]
no problem, thanks for the super useful library!
